### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by dekoza** [Northfear/stratagus-vita#2]
There's this part in the README that gives me problems:
```
Copy scripts/wc2-config.lua for Wargus or scripts/wc1-config.lua for War1gus 
and paste the file into ux0:data/Wargus/scripts//ux0:data/War1gus/scripts/.
```

Where are those files? They're not in `stratagus_data.zip`

**Comment by Northfear** [comment]
That's right, they're not. Basically you'll have to install PC version of Wargus first (and extract Warcraft data with it) and then copy extracted data over to Vita. These file are supposed to be located inside the installed Wargus folder on PC.

**Comment by dekoza** [comment]
I got them installed with the version you mentioned - 3.1.2 - and those scripts are not there.

**Comment by dekoza** [comment]
I got the script after installing git version on Linux.

**Comment by Northfear** [comment]
Kinda weird that they were not there, but I'm glad that you got it figured out
